version: '3.4'
services:
  app:
    build:
      context: .
      target: build
    environment:
      - NODE_ENV=development
      - NODE_CONFIG_ENV=development
    networks:
      - default
    ports:
      - '4000:4000'
    command: yarn watch
    volumes:
      - '.:/code'
      - /code/node_modules
networks:
  default: {}
